name: Pipeline
run-name: ${{ github.ref }} on ${{ github.repository }} is being built and tested out Github actions
on: 
    push:
        branches:
            - 'main'
            - 'development'
            - "add/**"
    pull_request:
jobs:
    Test-Engine:
        strategy:
            fail-fast: false
            matrix:
                compiler: ["GCC", "Clang"]
                config: ["Debug", "Release"]
                build_shared: [0, 1]
                os: [ubuntu-latest, windows-latest]
                include: 
                    - os: windows-latest
                      build_shared: 0
                      config: "Debug"
                      compiler: "MSVC"
                    - os: windows-latest
                      build_shared: 0
                      config: "Release"
                      compiler: "MSVC"
                    - os: windows-latest
                      build_shared: 1
                      config: "Debug"
                      compiler: "MSVC"
                    - os: windows-latest
                      build_shared: 1
                      config: "Release"
                      compiler: "MSVC"
        runs-on: ${{ matrix.os }}
        steps:
            - name: build on ${{ matrix.os }} with compiler is ${{ matrix.compiler }} and BUILD_SHARED_LIBS=${{ matrix.build_shared }} in config=${{ matrix.config }}
              run: echo "information os=${{ matrix.os }} compiler=${{ matrix.compiler }} build_shared=${{ matrix.build_shared }} config=${{ matrix.config }}"
            - name: Check GCC version
              if: ${{ matrix.compiler == 'GCC' }}
              run: gcc --version
            - name: Check Clang version
              if: ${{ matrix.compiler == 'Clang' }}
              run: clang --version
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install packages for Ubuntu
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: /bin/bash ./scripts/pre-installer/linux/debian/preinstaller.sh
            - name: Generate project for Visual Studio
              if: ${{ matrix.compiler == 'MSVC' }}
              run: cmake -S ./ -B ./build -DRUN_TEST=1 -DBUILD_SHARED_LIBS=${{ matrix.build_shared }}
            - name: Generate project for Unix makefile
              if: ${{ matrix.compiler != 'MSVC' }}
              run: cmake -S ./ -B ./build -DRUN_TEST=1 -DBUILD_SHARED_LIBS=${{ matrix.build_shared }} -G "Unix Makefiles"
            - name: Build project
              run: cmake --build build --config ${{ matrix.config }}
            - name: run test for MSVC
              if: ${{ matrix.compiler == 'MSVC' }}
              run: .\build\out\${{ matrix.config }}\engine_test.exe --gtest_output="xml:build/test-results.xml"
            - name: run test for Unix makefile
              if: ${{ matrix.compiler != 'MSVC' }}
              run: ./build/out/engine_test --gtest_output="xml:build/test-results.xml"